apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-site
  annotations:
    backstage.io/techdocs-ref: value
    github.com/project-slug: tommewong/demo-site
spec:
  type: other
  lifecycle: unknown
  owner: guests
