site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/backstage/backstage
edit_uri: edit/master/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - What is Backstage?: 'README.md'
  - api:
      - API: 'api/backend.md'
